/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as RenometaConnectRouteImport } from './routes/renometa-connect'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MultiChannelInboxRouteImport } from './routes/multi-channel-inbox'
import { Route as MarketingFollowUpAutomationRouteImport } from './routes/marketing-follow-up-automation'
import { Route as GrowthOperationsRouteImport } from './routes/growth-operations'
import { Route as CustomAiSolutionsRouteImport } from './routes/custom-ai-solutions'
import { Route as CrmSalesRouteImport } from './routes/crm-sales'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AiWebsiteSystemsRouteImport } from './routes/ai-website-systems'
import { Route as AiCenterRouteImport } from './routes/ai-center'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const RenometaConnectRoute = RenometaConnectRouteImport.update({
  id: '/renometa-connect',
  path: '/renometa-connect',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiChannelInboxRoute = MultiChannelInboxRouteImport.update({
  id: '/multi-channel-inbox',
  path: '/multi-channel-inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingFollowUpAutomationRoute =
  MarketingFollowUpAutomationRouteImport.update({
    id: '/marketing-follow-up-automation',
    path: '/marketing-follow-up-automation',
    getParentRoute: () => rootRouteImport,
  } as any)
const GrowthOperationsRoute = GrowthOperationsRouteImport.update({
  id: '/growth-operations',
  path: '/growth-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomAiSolutionsRoute = CustomAiSolutionsRouteImport.update({
  id: '/custom-ai-solutions',
  path: '/custom-ai-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmSalesRoute = CrmSalesRouteImport.update({
  id: '/crm-sales',
  path: '/crm-sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AiWebsiteSystemsRoute = AiWebsiteSystemsRouteImport.update({
  id: '/ai-website-systems',
  path: '/ai-website-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCenterRoute = AiCenterRouteImport.update({
  id: '/ai-center',
  path: '/ai-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-center': typeof AiCenterRoute
  '/ai-website-systems': typeof AiWebsiteSystemsRoute
  '/contact': typeof ContactRoute
  '/crm-sales': typeof CrmSalesRoute
  '/custom-ai-solutions': typeof CustomAiSolutionsRoute
  '/growth-operations': typeof GrowthOperationsRoute
  '/marketing-follow-up-automation': typeof MarketingFollowUpAutomationRoute
  '/multi-channel-inbox': typeof MultiChannelInboxRoute
  '/pricing': typeof PricingRoute
  '/renometa-connect': typeof RenometaConnectRoute
  '/solutions': typeof SolutionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-center': typeof AiCenterRoute
  '/ai-website-systems': typeof AiWebsiteSystemsRoute
  '/contact': typeof ContactRoute
  '/crm-sales': typeof CrmSalesRoute
  '/custom-ai-solutions': typeof CustomAiSolutionsRoute
  '/growth-operations': typeof GrowthOperationsRoute
  '/marketing-follow-up-automation': typeof MarketingFollowUpAutomationRoute
  '/multi-channel-inbox': typeof MultiChannelInboxRoute
  '/pricing': typeof PricingRoute
  '/renometa-connect': typeof RenometaConnectRoute
  '/solutions': typeof SolutionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-center': typeof AiCenterRoute
  '/ai-website-systems': typeof AiWebsiteSystemsRoute
  '/contact': typeof ContactRoute
  '/crm-sales': typeof CrmSalesRoute
  '/custom-ai-solutions': typeof CustomAiSolutionsRoute
  '/growth-operations': typeof GrowthOperationsRoute
  '/marketing-follow-up-automation': typeof MarketingFollowUpAutomationRoute
  '/multi-channel-inbox': typeof MultiChannelInboxRoute
  '/pricing': typeof PricingRoute
  '/renometa-connect': typeof RenometaConnectRoute
  '/solutions': typeof SolutionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-center'
    | '/ai-website-systems'
    | '/contact'
    | '/crm-sales'
    | '/custom-ai-solutions'
    | '/growth-operations'
    | '/marketing-follow-up-automation'
    | '/multi-channel-inbox'
    | '/pricing'
    | '/renometa-connect'
    | '/solutions'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-center'
    | '/ai-website-systems'
    | '/contact'
    | '/crm-sales'
    | '/custom-ai-solutions'
    | '/growth-operations'
    | '/marketing-follow-up-automation'
    | '/multi-channel-inbox'
    | '/pricing'
    | '/renometa-connect'
    | '/solutions'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-center'
    | '/ai-website-systems'
    | '/contact'
    | '/crm-sales'
    | '/custom-ai-solutions'
    | '/growth-operations'
    | '/marketing-follow-up-automation'
    | '/multi-channel-inbox'
    | '/pricing'
    | '/renometa-connect'
    | '/solutions'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiCenterRoute: typeof AiCenterRoute
  AiWebsiteSystemsRoute: typeof AiWebsiteSystemsRoute
  ContactRoute: typeof ContactRoute
  CrmSalesRoute: typeof CrmSalesRoute
  CustomAiSolutionsRoute: typeof CustomAiSolutionsRoute
  GrowthOperationsRoute: typeof GrowthOperationsRoute
  MarketingFollowUpAutomationRoute: typeof MarketingFollowUpAutomationRoute
  MultiChannelInboxRoute: typeof MultiChannelInboxRoute
  PricingRoute: typeof PricingRoute
  RenometaConnectRoute: typeof RenometaConnectRoute
  SolutionsRoute: typeof SolutionsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renometa-connect': {
      id: '/renometa-connect'
      path: '/renometa-connect'
      fullPath: '/renometa-connect'
      preLoaderRoute: typeof RenometaConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multi-channel-inbox': {
      id: '/multi-channel-inbox'
      path: '/multi-channel-inbox'
      fullPath: '/multi-channel-inbox'
      preLoaderRoute: typeof MultiChannelInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing-follow-up-automation': {
      id: '/marketing-follow-up-automation'
      path: '/marketing-follow-up-automation'
      fullPath: '/marketing-follow-up-automation'
      preLoaderRoute: typeof MarketingFollowUpAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth-operations': {
      id: '/growth-operations'
      path: '/growth-operations'
      fullPath: '/growth-operations'
      preLoaderRoute: typeof GrowthOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-ai-solutions': {
      id: '/custom-ai-solutions'
      path: '/custom-ai-solutions'
      fullPath: '/custom-ai-solutions'
      preLoaderRoute: typeof CustomAiSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm-sales': {
      id: '/crm-sales'
      path: '/crm-sales'
      fullPath: '/crm-sales'
      preLoaderRoute: typeof CrmSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-website-systems': {
      id: '/ai-website-systems'
      path: '/ai-website-systems'
      fullPath: '/ai-website-systems'
      preLoaderRoute: typeof AiWebsiteSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-center': {
      id: '/ai-center'
      path: '/ai-center'
      fullPath: '/ai-center'
      preLoaderRoute: typeof AiCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiCenterRoute: AiCenterRoute,
  AiWebsiteSystemsRoute: AiWebsiteSystemsRoute,
  ContactRoute: ContactRoute,
  CrmSalesRoute: CrmSalesRoute,
  CustomAiSolutionsRoute: CustomAiSolutionsRoute,
  GrowthOperationsRoute: GrowthOperationsRoute,
  MarketingFollowUpAutomationRoute: MarketingFollowUpAutomationRoute,
  MultiChannelInboxRoute: MultiChannelInboxRoute,
  PricingRoute: PricingRoute,
  RenometaConnectRoute: RenometaConnectRoute,
  SolutionsRoute: SolutionsRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
