create extension if not exists vector;

create table if not exists public.agent_requests (
  id uuid primary key,
  name text not null,
  email text not null,
  company_name text not null,
  company_site text not null,
  status text not null default 'pending',
  progress double precision not null default 0 check (progress >= 0 and progress <= 1),
  error_message text,
  created_at timestamptz not null default now()
);

create table if not exists public.agent_knowledge_base (
  id uuid primary key,
  user_request_id uuid not null references public.agent_requests(id) on delete cascade,
  content text not null,
  embedding vector(1536) not null,
  source_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.agent_conversations (
  id bigint generated by default as identity primary key,
  user_request_id uuid not null references public.agent_requests(id) on delete cascade,
  question text not null,
  answer text not null,
  created_at timestamptz not null default now()
);

create index if not exists agent_requests_email_created_at_idx
  on public.agent_requests (email, created_at desc);
create index if not exists agent_conversations_request_created_at_idx
  on public.agent_conversations (user_request_id, created_at desc);
create index if not exists agent_knowledge_base_request_idx
  on public.agent_knowledge_base (user_request_id);

alter table public.agent_requests enable row level security;
alter table public.agent_knowledge_base enable row level security;
alter table public.agent_conversations enable row level security;

create or replace function public.match_documents(
  query_embedding vector(1536),
  match_threshold double precision,
  match_count integer,
  filter_user_request_id uuid
)
returns table (
  id uuid,
  content text,
  source_url text,
  user_request_id uuid,
  similarity double precision
)
language sql
stable
security definer
set search_path = public
as $$
  select
    kb.id,
    kb.content,
    kb.source_url,
    kb.user_request_id,
    1 - (kb.embedding <=> query_embedding) as similarity
  from public.agent_knowledge_base kb
  where kb.user_request_id = filter_user_request_id
    and 1 - (kb.embedding <=> query_embedding) > match_threshold
  order by kb.embedding <=> query_embedding
  limit greatest(match_count, 0);
$$;

revoke all on function public.match_documents(vector, double precision, integer, uuid) from public;
grant execute on function public.match_documents(vector, double precision, integer, uuid) to service_role;
